server:
  port: 8888
  http2:
    enabled: true
  ssl:
    enabled: false
spring:
  cloud:
    loadbalancer:
      cache:
        enabled: true
        caffeine:
          spec: initialCapacity=256,expireAfterWrite=35s
  application:
    name: api-gateway



